spring.application.name=tpdindustrial
server.port=9098
#server.port=8080
# Configuración de PostgreSQL
spring.datasource.url=jdbc:postgresql://192.168.1.29/tpdindustrialsas
#spring.datasource.url=jdbc:postgresql://10.225.7.238/tpdindustrialsas
#spring.datasource.url=jdbc:postgresql://167.86.118.154:5432/metalelectricagmd
spring.datasource.username=postgres
spring.datasource.password=1234

spring.datasource.driver-class-name=org.postgresql.Driver
logging.level.org.springframework=error
logging.pattern.dateformat=hh.mm.ss
logging.pattern.console=%d{HH:mm:ss} - %msg%n

#logging.level.org.springframework.security=DEBUG
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update 
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=true
spring.security.user.name=miguel
spring.security.user.password=123456789
#ruta.carpeta.imagenes=//Users//miguelarcadioarangoluna//Documents/upload/CARPETA/
# correos
spring.mail.host=mail.tpdindustrial.co
spring.mail.port=587
spring.mail.username=miguel.arango@tpdindustrial.co
spring.mail.password=miguel12402047
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=arcadio37@gmail.com
#spring.mail.password=tu_contraseña
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true

nombre.profesion = Ingeniero Electronico